3rdparty/dev-tools

README.md, bootstrap
For now if you do git clone from `eventuals|eventuals-grpc|stout`
repos you will have already the symlink to the `clang-format` file
whick points to this repo. So there is no need to do it in
`bootstrap` file.
=> Remove symlink to `.clang-format` in bootstrap

measure_flakiness.sh
Sample output:
```bash
$ ./measure_flakiness.sh "/usr/bin/false"
Running the following command 100 times to measure flakiness: /usr/bin/false
0/100 runs succeeded (100% flaky)
$ ./measure_flakiness.sh "/usr/bin/true"
Running the following command 100 times to measure flakiness: /usr/bin/true
100/100 runs succeeded (0% flaky)
```
=> Add a script to measure the flakiness of a command

measure_flakiness.sh
Also add streaming run count which helps track progress for long-running
commands.
Sample output:
```bash
$ RUN_COUNT=5 ./measure_flakiness.sh true
Running the following command 5 times to measure flakiness: true
Run 1 of 5
Run 2 of 5
Run 3 of 5
Run 4 of 5
Run 5 of 5
5/5 runs succeeded (0% flaky)
```
=> Make flakiness script run count configurable

check-code-style/action.yml
We use `${{ github.action_path  }}` to be aware of the full path
where this action is located. So, we can easily run this action
non depending on the path where the submodule with this action is
located.
=> Use github action path variable

check-code-style/action.yml
Due to input parameter 'inputs.os' we can do some preparations for
code style checks depending on os. Thus the 'caller' action could
only call this 'composite' action and there is no any need to
create symlink or even install clang-format in the 'caller' action.
=> Add input parameter

.bazelrc
This allows you to build targets or tests with `--config=asan` and get
detailed debugging information for bad memory access.
Adding this in dev-tools so it can be easily shared across repos: we'll
use this a lot for any C++ development.
=> Add an "asan" bazel config to debug crashes

.bazelrc
`--test_output=errors` should probably be specified on `test` (since it's a test option) rather than `build` (though `build` seems to work just fine).
=> Cleaner .bazelrc test_output config

Dockerfile.dazel
We are currently using `dazel` in three places. I believe that we should
be able to use the same `Dockerfile` for all three cases. So to ease
maintainability and streamline development I propose this new(ish)
`Dockerfile` based on the updated one used in `respect`.
=> Add Dockerfile.dazel to repo

Dockerfile.dazel
Bazel 5 used to generate build errors on our code:
https://github.com/3rdparty/eventuals-grpc/issues/65
but that was fixed with a newer gRPC release:
https://github.com/3rdparty/eventuals/pull/247
=> Update to bazel 5.0.0

.github/workflows/scripts/check-if-issue-and-pr-exist.sh, .github/workflows/scripts/per-submodule-build-matrix.sh, .github/workflows/submodules-sync.yml
The PR addresses issue https://github.com/3rdparty/dev-tools/issues/41.
I am going to cover the issue in the following steps and order (with minimal downtime considered):
**1. Upload bash scripts that are supposed to replace shell steps in Submodules-sync workflow. - [part_1](https://github.com/3rdparty/dev-tools/pull/42).**
2. Add `inputs` to the workflow to be able to specify scripts directory manually from parent workflow (`respect` and `eventuals` accordingly) because it could be different from repos to repo. - [part_2](https://github.com/3rdparty/dev-tools/pull/43).
3. Modify the workflow to use bash scripts instead of shell steps. - [part_2](https://github.com/3rdparty/dev-tools/pull/43)
4. Update the Submodules-sync workflow to use `inputs` in `respect` repo. - …
=> [Submodules-sync workflow update part_1] Upload bash scripts

.github/workflows/scripts/check-if-issue-and-pr-exist.sh, .github/workflows/scripts/per-submodule-build-matrix.sh, .github/workflows/submodules-sync.yml
The PR addresses issue https://github.com/3rdparty/dev-tools/issues/41.
I am going to cover the issue in the following steps and order (with minimal downtime considered):
1. Upload bash scripts that are supposed to replace shell steps in Submodules-sync workflow. - [part_1](https://github.com/3rdparty/dev-tools/pull/42).
**2. Add `inputs` to the workflow to be able to specify scripts directory manually from parent workflow (`respect` and `eventuals` accordingly) because it could be different from repos to repo. - [part_2](https://github.com/3rdparty/dev-tools/pull/43).**
**3. Modify the workflow to use bash scripts instead of shell steps. - [part_2](https://github.com/3rdparty/dev-tools/pull/43)**
4. Update the Submodules-sync workflow to use `inputs` in `respect` repo. - …
=> [Submodules-sync workflow update part_2] Wrap shell steps to scripts

.github/workflows/scripts/per-submodule-build-matrix.sh
Fixing path of file `.gitmodules` in script.
Related issue: https://github.com/3rdparty/eventuals/issues/369.
=> [Submodules-sync] Fix path in script

.style.yapf
Before this PR we were using custom configuration in
`reboot-dev/respect`'s `.vscode.json` to set the desired YAPF style for
our Python code.
With this PR we create a `.style.yapf` file that matches that style here 
in `dev-tools`, and make it available for other repos to symlink. This is
a step towards using the same Python style for all repos.
=> Add .style.yapf file for standard YAPF (Python) style

.mergequeue/config.yml
We've previously activated MergeQueue for ~all our other repos, and it's
confusing that dev-tools doesn't use it yet. This PR checks in our
standard MergeQueue config.
=> Activate MergeQueue for the 3rdparty/dev-tools repo

check-code-style/action.yml
In #48 we added a standard `.style.yapf` file to teach all our YAPF (Python formatters) how to behave.
This PR adds YAPF to our set of standard formatting checks run at PR-time. This check has been shown to work in https://github.com/reboot-dev/respect/pull/422 - but that PR was a little short-sighted since it only acts on the `reboot-dev/respect` repo. This PR takes the same awesome check but makes it available to all our repos.
(Subsequent PRs will move `reboot-dev/respect` over to using that standard formatting check workflow)
Note that automated formatting had some opinions about quotes in YAML files. I deny everything. 🤷🏻 
TESTED: prototyped using this check in the `reboot-dev/pyprotoc-plugin` repo, which is another place it'll get used in the future.
=> Add YAPF to the standard formatting checks

check-code-style/check_style.sh
The `respect` repo has some lines (e.g. commented URLs) that cannot be broken to <80 characters. We still prefer to use this custom script to check line length (rather than enabling the feature from clang), but we need to be able to skip those lines when necessary.
=> Add option to skip length check for a line

check-code-style/check_style.sh
Before this commit, if a line was skipped, the increment of the line number was skipped too, leading to the output from the script displaying wrong line numbers.
In certain cases, adding a comment on the line above a too long line is not an option, as clang format indents said comment so far that it itself exceeds the line limit. This commit resolves this pickle by also skipping lines that has the magic incantation at the very end of the line.
```cpp
// The below line will be skipped
auto some_very_long_line_calling_weird_code_instead_of_dancing();  // check_line_length skip
// However, this line - despite containing the string "check_line_length skip" - will still be subject to the line length check
// as the token is not at the end of the line.
```
Thirdly, this commit contains some …
=> Fix line count bug, add EOL option for line skip

check-code-style/action.yml
GitHub recently removed `brew` from `PATH` in this [PR](https://github.com/actions/runner-images/pull/6240).
This commit uses the full path on Linux as suggested [here](https://github.com/mikhailkoliada/runner-images/blob/935669cb34f634093417b92e4590bf819a2ba915/images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1#L93).
=> Use full path to 'brew' since GitHub recently removed it from PATH

check-code-style/action.yml
With #58 we updated the path used to invoke `brew`, since it was removed from the `$PATH`. However, it turns out that the binaries installed via `brew`, notably our `buildifier`, had also fallen off the PATH.
This PR completes the suggestion quoted in #58 by `eval`ing `brew shellenv`, which will place `buildifier` back on the PATH.
TESTED: ran this action from a bogus PR
(https://github.com/reboot-dev/respect/pull/968) and saw it
pass, after it had previously failed.
=> Correct PATH to include 'buildifier'

.github/workflows/submodules-sync.yml
Before this PR, `submodule-sync.yml` assumed that every PR it creates will run exactly one status check called "Build and Test", which it will wait to complete before merging. It would sit there and wait, burning an action runner's worth of resources, while waiting for this test to complete.
With our recent changes to `respect`'s workflows that repo no longer has such a status check, meaning that its submodule syncs were never completing. Also, our tests run long enough now that the wait time for them to complete is burning a lot of action runner resources.
This PR removes the requirement that `submodule-sync` wait for a status check. It will immediately assign the `mergequeue-ready` label and stop, letting mergequeue take it from there.
The downside to this is that `submodule-sync` will …
=> Fix submodule sync

check-code-style/check_style_bzl.sh
Just running `buildifier {file}` often won't catch the issues the tool finds, since `warnings=all` isn't the default.
=> Update buildifier fix command suggested to user

.github/workflows/code_formatting.yaml, check-code-style/action.yml
This PR has this repo use its own formatting check, already used by
other repos, when a PR is opened. This ensures that configuration files
(e.g. the YAML and JSON now checked with https://github.com/3rdparty/dev-tools/pull/63) that this repo provides to
other repos match its own formatting rules.
Note: currently based off #63, base branch will change automatically when that PR is submitted.
=> Run own code format check on PRs

.isort.cfg
`isort` is a tool that helps us sort our Python imports in a consistent way. By having a shared configuration file we can have our VSCode auto-format our files as we write them.
A future PR can add pre-submit checks that new Python code is formatted with `isort`, but we'll first need to bring all repos in line with this new style.
Here's the effect `isort` will have on our existing code:
* https://github.com/reboot-dev/respect/pull/1091
* https://github.com/reboot-dev/respect-examples/pull/29
=> Introduce shared isort config file

check-code-style/action.yml
In #66 we introduced an `isort` config that repos can use to automatically sort Python `import`s. This commit adds a check to ensure that the imports are indeed sorted. This check is active only if `isort` is activated in the repo, as indicated by an `.isort.cfg` file being present at the top-level of the repo.
TESTED: saw check correctly flag a non-`isort`ed file in [this test run](https://github.com/reboot-dev/respect/actions/runs/3567763894/jobs/5995847235).
PS: the warning flagged in that test run, about `::set-output` being deprecated, will be addressed in https://github.com/3rdparty/dev-tools/issues/68.
=> Add `isort` code style check

.github/workflows/scripts/per-submodule-build-matrix.sh, check-code-style/action.yml
Replacing it with `$GITHUB_OUTPUT` as described here:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Part of https://github.com/3rdparty/dev-tools/issues/68
=> Remove deprecated use of ::set-output

.isort.cfg, check-code-style/action.yml
The two issues are:
1. isort turns out to have difficulties separating first-party and third-party libraries, which it uses to create separate sections of imports. This results in machine-dependent sorting of imports, which is bad. For example, the PR in reboot-dev/respect-examples#32 is failing to merge because of this mismatch. Since we actually don't care about the sections (we weren't using them before), disable sections to get reliable import ordering across machines.
2. The isort GitHub Action turns out to swallow important debug info because it swallows STDOUT. Install and run `isort` manually instead.
=> Fix two issues with isort configuration and check

check-code-style/action.yml
We were bitten by https://github.com/creyD/prettier_action/issues/113, which breaks our code style check and therefore our ability to submit PRs.
The fix is to update that action to v4.3. And to yell and gesticulate wildly about how GitHub Actions shouldn't change the major version of the `npm` runtime without us taking action!
=> Update `prettier_action` from broken v4.2 to v4.3

check-code-style/check_style.sh
Before this commit we couldn't get `check_style.sh` to ignore a whole file; we've gotten pretty far by ignoring only singular lines!
However, now we need to copy in some files that aren't produced by us, and that we can't reasonably reformat to fit our style. So we need to have a way to ignore whole files.
This commit adds a new `check_line_length ignore` option, which will cause the whole remainder of the file it is found in to be ignored.
=> Line length: ignore whole files

pre-commit
Fixes https://github.com/reboot-dev/respect/issues/1408 by extending the pre-commit hook to also checking that no changes were made to the staged files.
=> Check for changes to staged files

check-style.sh, pre-commit
This PR fixes https://github.com/reboot-dev/respect/issues/1410 by
1) Adding an error message in case of a failed pre-commit:
```
WARNING NO FILES WERE COMMITTED: One or more pre-commit checks failed!
Please, carefully check the output above to see what went wrong.
Hint: Code style check failed.
```
2) Suppresses some of the verbose output from `prettier` in the `check-style.sh` script that might cause confusion.
=> Improve error message for pre-commit hook

pre-commit, pre-commit-print-error
Companion to https://github.com/reboot-dev/respect/pull/1829.
Now that we have pre-commit scripts in multiple places, it's nice to be able to use the `print_error` function separately from the rest of the pre-commit script.
=> Factor out print_error from pre-commit

.github/workflows/scripts/check-if-issue-and-pr-exist.sh
This script was deleted in https://github.com/3rdparty/dev-tools/commit/38885744437561123ca4bbb7d39d261ac9b6910f
but it is not a dead code and used by `eventuals`
Since `eventuals` checks were down, it wasn't possible to update submodule `dev-tools` there, but after checks were green we got an error.
https://github.com/3rdparty/eventuals/actions/runs/8191190953/job/22399846854
=> Restore 'eventuals' needed script

.style.yapf
In particular, this means that `yapf` will respect commas and not try and do weird line wrapping even though we have included a comma!!!
=> Make keyword/named args work the same as unnamed args

check-style.sh
Fixes https://github.com/reboot-dev/respect/issues/3758.
=> Include `*.mdx` in snippets checks.

.github/workflows/scripts/per-submodule-build-matrix.sh
Before this commit, `per-submodule-build-matrix.sh` assumed that the top level of the repo it was syncing was at `../../../../../`, which happened to be true for all of our repos. As of [reboot-dev/respect@`323ce51` (#3786)](https://github.com/reboot-dev/respect/pull/3786/commits/323ce51a506e99ae5452d6c584475edf4a8620fc) however, that is no longer true.
This commit makes the script look up the top-level of its containing repo dynamically, with its only
assumption being that the script is being run from a submodule itself - which still holds.
TESTED: checked that the `submodule-sync` workflow passes again for the `reboot-dev/respect` repo
where it was previously broken.
=> `submodule-sync`: make fewer path assumptions

.github/workflows/code_formatting.yaml, check-code-style/action.yml
Partially completes https://github.com/reboot-dev/mono/issues/4287 and https://github.com/reboot-dev/mono/issues/4284
=> Upgrade to LLVM 19

check-style.sh
As previously coded, this emits the delightfully cryptic error message
```
File "/home/runner/work/stout/stout/./dev-tools/README.md", line 3
Collection of developer scripts, files, etc, for improving the developer process.
^^
SyntaxError: invalid syntax
```
Because the failure to find the unindent script results in trying to run `python README.md`
=> Fix error when unindent_auto_doc_script is not found

check-style.sh
Our style checks were adding problems when adding symlinks to directories:
* `prettier` will error out if told to format a directory that doesn't contain any files it can format.
* `git` will report new symlinks to directories as new files.
* `prettier` will interpret symlinks to directories as directories.
* Therefore, if adding a symlink to a directory that doesn't have any `prettier`-relevant files, `prettier` will error out.
We avoid this (and any other symlink confusion) by excluding symlinks from style checks. By definition they'll point to a real file or directory that will be getting formatted anyway.
=> Ignore symlinks in style checks
